name: 'docker-example-mssql'
services:
  mssql:
    build: .
    container_name: mssql_server
    environment:
      SA_PASSWORD: StrongPassword123
      ACCEPT_EULA: 'Y'
    volumes:
      - ./sql-volume:/var/opt/mssql/data
    ports:
      - "1433:1433"
    restart: unless-stopped
